### ISSUE TITLE
Fix and improvement around picking/shipping

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-dist#41]
TODO: please create a cli migration script to:
* fix the pricing slot's location. This one is wrong (the right one already exists): 
![image](https://user-images.githubusercontent.com/1264789/39688303-58ac4584-51d2-11e8-8604-64c65b4ca80b.png)
* add a "Der Kurier" Lieferweg (shipper) as documented here: https://github.com/metasfresh/metasfresh/issues/3926

**Comment by metas-lc** [comment]
IT
1. checked picking slots after new database was up
=> picking slots locations are the correct ones (picking) OK
2. go to shipper window => there is a der kurier one OK
should it have bpartner of org set? currently is none ?

**Comment by metas-rc** [comment]
I added the partner. It's only dummy data and without that partner set we are not able to use the functionality.

**Comment by metas-lc** [comment]
IT
der kurier shipper has bpartner set OK
