### ISSUE TITLE
swingUI - add startup parameters so the client posts documents locally

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-dist#50]

**Comment by metas-ts** [comment]
hi @teosarca 
given issue [#4345](https://github.com/metasfresh/metasfresh/issues/4345) Make accounting async ,
what should we now cleanup from AD_SysConfig and bat/sh files?

**Comment by teosarca** [comment]
everything which is related to client accounting.

**Comment by teosarca** [comment]
which means:
* some CLIENT_ACCOUNTING sysconfig (not sure the exact name). We have that in bat/sh files too
* AD_Client.IsPostImmediate flag
